login:
    path:     /login
    defaults: { _controller: AppBundle:User:login }

login_check:
    path:     /login_check

logout:
    path: /logout

register:
    path:     /register
    defaults: { _controller: AppBundle:User:register }
    
user_edit:
    path:     /my-data
    defaults: { _controller: AppBundle:User:editUser }

user_list:
    path:     /people
    defaults: { _controller: AppBundle:User:users }
    
user_search:
    path:     /search
    defaults: { _controller: AppBundle:User:search }
    
ajax_nick_test:
    path:     /nick-test
    defaults: { _controller: AppBundle:User:nickTest }
    methods: [POST]
    
ajax_email_test:
    path:     /email-test
    defaults: { _controller: AppBundle:User:emailTest }
    methods: [POST]