BackendBundle\Entity\User:
    properties:
        name:
            - NotBlank: {message: "El campo nombre no puede estar vacio"}
            - Regex: 
                pattern: '/\d/'
                match:   false
                message: El nombre no puede contener valores númericos
        surname:
            - NotBlank: {message: "El campo apellidos no puede estar vacio"}
            - Regex: 
                pattern: '/\d/'
                match:   false
                message: El apellido no puede contener valores númericos
        nick:
            - NotBlank: {message: "El campo nick no puede estar vacio"}
        email:
            - NotBlank: {message: "El campo email no puede estar vacio"}
            - Email:
                message: El email {{ value }} no es válido
                checkMX: false